USE HumanResources ;
GO

CREATE MASTER KEY ENCRYPTION BY PASSWORD = 'Pa$$w0rd' ;
GO

OPEN MASTER KEY DECRYPTION BY PASSWORD = 'Pa$$w0rd';  
BACKUP MASTER KEY TO FILE = 'c:\keys\HumanResourcesMasterKey.key'
    ENCRYPTION BY PASSWORD = 'Pa$$w0rd' ;  
GO  

CREATE CERTIFICATE SalaryCert
WITH SUBJECT = 'Employee Saleries' ;
GO

CREATE SYMMETRIC KEY SalaryKey
WITH ALGORITHM = AES_128 
ENCRYPTION BY CERTIFICATE SalaryCert ;
GO
